package com.danhuy.common_service.enums;

public enum SagaStep {
  CREATE_ORDER,
  CHECK_INVENTORY,
  PROCESS_PAYMENT,
  UPDATE_INVENTORY,
  ORDER_COMPLETED,
  REFUND_PAYMENT,
  ORDER_CANCELLED,
  RESERVE_INVENTORY,
  COMMIT_INVENTORY,
  RELEASE_INVENTORY
}
